# Generated by Django 6.0.3 on 2026-03-17 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('biografia', models.TextField()),
                ('imagen_perfil', models.ImageField(blank=True, null=True, upload_to='artistas/')),
            ],
        ),
        migrations.CreateModel(
            name='HitoLineaTiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('evento', models.CharField(max_length=300)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='artistas.artista')),
            ],
            options={
                'ordering': ['anio'],
            },
        ),
        migrations.CreateModel(
            name='ObraDestacada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo_audio', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='artistas.artista')),
            ],
        ),
    ]
