# Generated by Django 6.0.1 on 2026-03-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='composiciones_resumen',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='legado_resumen',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='obras_destacadas_resumen',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='periodo_vida',
            field=models.CharField(blank=True, help_text='Ej: 1 de marzo de 1876 – 1935', max_length=200),
        ),
    ]
