# Generated by Django 6.0.3 on 2026-04-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0003_artista_biografia_en_artista_biografia_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='esencia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='esencia_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artista',
            name='esencia_fr',
            field=models.TextField(blank=True),
        ),
    ]
