# Generated by Django 6.0.3 on 2026-04-15 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artistas', '0003_artista_biografia_en_artista_biografia_fr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroMusical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL amigable para el género.', unique=True)),
                ('descripcion_historica', models.TextField()),
                ('descripcion_historica_en', models.TextField(blank=True)),
                ('descripcion_historica_fr', models.TextField(blank=True)),
                ('caracteristicas_musicales', models.TextField()),
                ('caracteristicas_musicales_en', models.TextField(blank=True)),
                ('caracteristicas_musicales_fr', models.TextField(blank=True)),
                ('imagen_representativa', models.ImageField(blank=True, null=True, upload_to='musica/generos/')),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('descripcion_en', models.TextField(blank=True)),
                ('descripcion_fr', models.TextField(blank=True)),
                ('archivo_audio', models.FileField(upload_to='musica/audios/')),
                ('fecha_lanzamiento', models.CharField(blank=True, help_text='Época o año relativo.', max_length=100)),
                ('compositor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canciones_musica_lojana', to='artistas.artista')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='musica.generomusical')),
            ],
        ),
        migrations.CreateModel(
            name='RecursoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('articulo', 'Artículo'), ('referencia', 'Referencia Cultural'), ('explicacion', 'Explicación')], default='articulo', max_length=50)),
                ('contenido', models.TextField()),
                ('contenido_en', models.TextField(blank=True)),
                ('contenido_fr', models.TextField(blank=True)),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_educativos', to='musica.generomusical')),
            ],
        ),
    ]
