# Generated by Django 6.0.3 on 2026-04-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='url_youtube',
            field=models.URLField(blank=True, help_text='Link de YouTube para reproducir si no hay archivo físico.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cancion',
            name='archivo_audio',
            field=models.FileField(blank=True, null=True, upload_to='musica/audios/'),
        ),
    ]
