# Generated by Django 6.0.3 on 2026-04-19 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0004_artista_esencia_artista_esencia_en_and_more'),
        ('gamificacion', '0003_logro_descripcion_en_logro_descripcion_fr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nombre_en', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('descripcion_en', models.TextField(blank=True)),
                ('puntos_requeridos', models.IntegerField(default=0)),
                ('icono', models.CharField(default='fas fa-star', max_length=100)),
                ('rareza', models.CharField(default='Común', max_length=50)),
                ('color_borde', models.CharField(default='#e3aa59', max_length=20)),
                ('artista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cromos', to='artistas.artista')),
            ],
        ),
    ]
